// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIFv5SYqGch0PuwVs_FLlG7XgASr29Cb4',
    appId: '1:893964794004:web:87ee344d57ebf810fddc81',
    messagingSenderId: '893964794004',
    projectId: 'manpower-fa519',
    authDomain: 'manpower-fa519.firebaseapp.com',
    storageBucket: 'manpower-fa519.firebasestorage.app',
    measurementId: 'G-P2HQDXFRGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bJp7-IsIW6dZPnr5tILvSLAl9IxRdys',
    appId: '1:893964794004:android:48e398144bf9dfdafddc81',
    messagingSenderId: '893964794004',
    projectId: 'manpower-fa519',
    storageBucket: 'manpower-fa519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-aMI9eC0EdnwKLmHVFh-5BKdumnSXS8',
    appId: '1:893964794004:ios:9dda9626b059be05fddc81',
    messagingSenderId: '893964794004',
    projectId: 'manpower-fa519',
    storageBucket: 'manpower-fa519.firebasestorage.app',
    iosBundleId: 'com.example.manpower',
  );

}